/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apu.gym;

import static apu.gym.Customer.customer;
import static apu.gym.Feedback.feedback;
import static apu.gym.User.user;
import javax.swing.table.DefaultTableModel;
import java.text.*;
import java.util.*;
import java.util.logging.*;
import javax.swing.*;


/**
 *
 * @author Acer
 */
public class CustomerHome extends javax.swing.JFrame {
    
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    
    Calendar cal = Calendar.getInstance();
    String allSession;
    
    /**
     * Creates new form TrainerHome
     */
    public CustomerHome() {
        initComponents();
        
        // icon to display APU logo for JFrame
        ImageIcon icon = new ImageIcon("src/apu/gym/images/logo.png"); // https://www.youtube.com/watch?v=Kmgo00avvEw
        setIconImage(icon.getImage());
        
        // icon to display background
        ImageIcon iconBgd = new ImageIcon("src/apu/gym/images/bgd.png"); // https://www.youtube.com/watch?v=Kmgo00avvEw
        bgd.setIcon(iconBgd);
        
        // display profile icon
        ImageIcon iconProfile = new ImageIcon("src/apu/gym/images/profile.png"); // https://www.youtube.com/watch?v=Kmgo00avvEw
        btnProfile.setIcon(iconProfile);
                
        // get details from txtfile and display training details
        allSession = customer.getTrainingSession();
        displaySession(allSession);
        
    }
    
    
    private void displaySession(String sessionStr){
        DefaultTableModel model = (DefaultTableModel)tblSession.getModel();
        model.setRowCount(0);  // remove previous records in table
        
        if (!sessionStr.equals("")){
            String[] sessions = sessionStr.split("\n");  // split string into arrays of session
            
            for (String session : sessions) {
                String[] data = session.split(";");
                String time = data[1] + "-" + data[2];
                String trainer = data[9] + " - @" + data[8];
                model.addRow(new Object[]{data[0], time, data[3], data[4], data[5], trainer});  // https://www.youtube.com/watch?v=F0Zq2fAUpXg&t=243s
            }
        }
    }
    
    
    void viewFeedback(){
        DefaultTableModel model = (DefaultTableModel)tblSession.getModel();

        if (tblSession.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Please select a row!", "Missing Input", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                int selectedRow = tblSession.getSelectedRow();
                String date = (String)model.getValueAt(selectedRow, 0);
                
                // check if today is before the selected date (feedback can only be viewed for past days or today)
                if (new Date().before(sdf.parse(date))){
                    JOptionPane.showMessageDialog(null, "Cannot view feedback on future date!", "Error", JOptionPane.ERROR_MESSAGE);
                }
                else {
                    feedback.setSessionDate(date);
                    feedback.setSessionTime((String)model.getValueAt(selectedRow, 1));
                    feedback.setCustomerUsername(user.getUsername());
                    String trainerUsername = (String)model.getValueAt(selectedRow, 5);
                    feedback.setTrainerUsername(trainerUsername.split("@")[1]);
                    
                    boolean success = customer.viewFeedback();
                    
                    if (success){
                        JOptionPane.showMessageDialog(null, "Rating: " + feedback.getRating() + "\nFeedback: " + feedback.getContent(), "Feedback", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(null, "The trainer has not provide any feedback yet!\nPlease try again later.", "Feedback Not Found", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (ParseException ex) {
                Logger.getLogger(CustomerHome.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.                                                    
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanelTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnProfile = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblTimetable = new javax.swing.JLabel();
        txtDate = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblSession = new javax.swing.JTable();
        btnFeedback = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        bgd = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Customer Homepage");

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMaximumSize(new java.awt.Dimension(950, 580));
        jPanel1.setMinimumSize(new java.awt.Dimension(950, 580));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 580));
        jPanel1.setLayout(null);

        jPanelTitle.setBackground(new java.awt.Color(255, 255, 204));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 139));
        lblTitle.setText("APU Gym Management System");

        btnProfile.setBackground(new java.awt.Color(153, 187, 255));
        btnProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProfile.setFocusable(false);
        btnProfile.setMaximumSize(new java.awt.Dimension(38, 38));
        btnProfile.setMinimumSize(new java.awt.Dimension(38, 38));
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 0, 0));
        btnLogout.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LOGOUT");
        btnLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.setFocusPainted(false);
        btnLogout.setFocusable(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitle)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jPanel1.add(jPanelTitle);
        jPanelTitle.setBounds(0, 0, 950, 90);

        lblTimetable.setBackground(new java.awt.Color(255, 255, 255));
        lblTimetable.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTimetable.setText("Timetable");
        jPanel1.add(lblTimetable);
        lblTimetable.setBounds(40, 120, 210, 44);

        txtDate.setFocusable(false);
        txtDate.setRequestFocusEnabled(false);
        txtDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtDatePropertyChange(evt);
            }
        });
        jPanel1.add(txtDate);
        txtDate.setBounds(650, 130, 150, 30);

        tblSession.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Time", "Duration", "Venue", "Level", "Trainer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSession.setGridColor(new java.awt.Color(255, 255, 204));
        tblSession.setMinimumSize(new java.awt.Dimension(75, 40));
        jScrollPane9.setViewportView(tblSession);

        btnFeedback.setBackground(new java.awt.Color(0, 102, 204));
        btnFeedback.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnFeedback.setForeground(new java.awt.Color(255, 255, 255));
        btnFeedback.setText("View Feedback");
        btnFeedback.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeedbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(40, 190, 880, 350);

        btnClear.setBackground(new java.awt.Color(255, 255, 153));
        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setText("Clear Selection");
        btnClear.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear);
        btnClear.setBounds(810, 130, 110, 30);

        bgd.setText("jLabel1");
        bgd.setMaximumSize(new java.awt.Dimension(950, 580));
        bgd.setMinimumSize(new java.awt.Dimension(950, 580));
        bgd.setOpaque(true);
        bgd.setPreferredSize(new java.awt.Dimension(950, 580));
        jPanel1.add(bgd);
        bgd.setBounds(0, 0, 950, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // confirm logout dialog
        int reply = JOptionPane.showConfirmDialog(null, "Do you want to Logout?", "Logout Confirmation", JOptionPane.YES_NO_OPTION);
        
        if (reply == JOptionPane.YES_OPTION){
            this.dispose();
            Login login = new Login();
            login.setVisible(true);
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        try {
            // transfer to Profile page
            this.dispose();
            CustomerProfile cp = new CustomerProfile();
            cp.setVisible(true);
        } catch (ParseException ex) {
            Logger.getLogger(CustomerHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeedbackActionPerformed
        viewFeedback();
    }//GEN-LAST:event_btnFeedbackActionPerformed

    private void txtDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtDatePropertyChange
        // get selected date
        Date selectedDate = txtDate.getDate();
        
        if (selectedDate != null){
            cal.clear();
            cal.setTime(selectedDate);
            
            // display session details for the selected date
            String session = customer.searchSession(sdf.format(selectedDate));
            displaySession(session);
        }
    }//GEN-LAST:event_txtDatePropertyChange

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtDate.setCalendar(null);  // remove selected date
        displaySession(allSession);  // display all training sessions
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnFeedback;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnProfile;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblTimetable;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblSession;
    private com.toedter.calendar.JDateChooser txtDate;
    // End of variables declaration//GEN-END:variables
}
